# - Locate CEGUI library
# This module defines
#  CEGUI_LIBRARY, the library to link against
#  CEGUI_FOUND, if false, do not try to link to CEGUI
#  CEGUI_INCLUDE_DIRS, where to find headers.

IF(CEGUI_LIBRARY AND CEGUI_INCLUDE_DIRS)
  # in cache already
  SET(CEGUI_FIND_QUIETLY TRUE)
ENDIF(CEGUI_LIBRARY AND CEGUI_INCLUDE_DIRS)


FIND_PATH(CEGUI_INCLUDE_DIR cegui-0/CEGUI/CEGUI.h PATH_SUFFIXES include)

FIND_LIBRARY(CEGUI_LIBRARY NAMES CEGUIBase-0_Static CEGUIBase-0_Static_d CEGUIBase-0 CEGUIBase-0_d)
FIND_LIBRARY(CEGUI_COMMONDIALOGS_LIBRARY NAMES CEGUICommonDialogs-0_Static CEGUICommonDialogs-0_Static_d CEGUICommonDialogs-0 CEGUICommonDialogs-0_d)
FIND_LIBRARY(CEGUI_OPENGLRENDERER_LIBRARY NAMES CEGUIOpenGLRenderer-0_Static CEGUIOpenGLRenderer-0_Static_d CEGUIOpenGLRenderer-0 CEGUIOpenGLRenderer-0_d)
if (WIN32)
	FIND_LIBRARY(CEGUI_COREWINDOWRENDERERSET_LIBRARY NAMES CEGUICoreWindowRendererSet_Static CEGUICoreWindowRendererSet_Static_d CEGUICoreWindowRendererSet CEGUICoreWindowRendererSet_d)
	FIND_LIBRARY(CEGUI_RAPIDXMLPARSER_LIBRARY NAMES CEGUIRapidXMLParser_Static CEGUIRapidXMLParser_Static_d CEGUIRapidXMLParser CEGUIRapidXMLParser_d)
	FIND_LIBRARY(CEGUI_STBIMAGECODEC_LIBRARY NAMES CEGUISTBImageCodec_Static CEGUISTBImageCodec_Static_d CEGUISTBImageCodec CEGUISTBImageCodec_d)
endif()

SET(CEGUI_LIBRARIES
	${CEGUI_LIBRARY}
	${CEGUI_COMMONDIALOGS_LIBRARY}
	${CEGUI_COREWINDOWRENDERERSET_LIBRARY}
	${CEGUI_OPENGLRENDERER_LIBRARY}
	${CEGUI_RAPIDXMLPARSER_LIBRARY}
	${CEGUI_STBIMAGECODEC_LIBRARY}
)

GET_FILENAME_COMPONENT(CEGUI_LIB_DIR ${CEGUI_LIBRARY} PATH CACHE)

IF(CEGUI_LIBRARY AND CEGUI_INCLUDE_DIRS)
  SET(CEGUI_FOUND "YES")
  SET(CEGUI_INCLUDE_DIRS "${CEGUI_INCLUDE_DIRS}/CEGUI")
  IF(NOT CEGUI_FIND_QUIETLY)
    MESSAGE(STATUS "Found CEGUI: ${CEGUI_LIBRARY}")
  ENDIF(NOT CEGUI_FIND_QUIETLY)
ELSE(CEGUI_LIBRARY AND CEGUI_INCLUDE_DIRS)
  IF(NOT CEGUI_FIND_QUIETLY)
    MESSAGE(STATUS "Warning: Unable to find CEGUI!")
  ENDIF(NOT CEGUI_FIND_QUIETLY)
ENDIF(CEGUI_LIBRARY AND CEGUI_INCLUDE_DIRS)
