find_path(LOGOG_INCLUDE_DIR logog/logog.hpp
   PATH_SUFFIXES include/logog logog)
find_library(LOGOG_LIBRARY logog)

message(LOGOG_INCLUDE_DIR)
message(LOGOG_LIBRARY)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LOGOG DEFAULT_MSG LOGOG_LIBRARY LOGOG_INCLUDE_DIR)

MARK_AS_ADVANCED(
  LOGOG_INCLUDE_DIR
  LOGOG_LIBRARY
)
