find_path(FREETYPE_INCLUDE_DIR freetype2/freetype/freetype.h)
find_library(FREETYPE_LIBRARY NAMES freetype freetyped)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(FREETYPE DEFAULT_MSG FREETYPE_LIBRARY FREETYPE_INCLUDE_DIR)

MARK_AS_ADVANCED(
  FREETYPE_INCLUDE_DIR
  FREETYPE_LIBRARY
)
